#!/usr/bin/env python
import os
import sys
import yaml

if len(sys.argv) > 1:
    directory = sys.argv[1]
else:
    directory = 'jekyll/content/terms'

filenames = os.listdir(directory)

file_data = {}
for fn in filenames:
    with open(os.sep.join([directory, fn])) as handle:
        content = handle.read()
        raw_metadata = content.split('---', 2)[1]
        metadata = yaml.load(raw_metadata)
        metadata['filename'] = fn
        file_data[fn] = metadata

for fn, md in file_data.iteritems():
    related_terms = md.get('related_terms', [])
    for term in related_terms:
        if not file_data.get(term + '.md'):
            print fn, "has misspelled term", term
