source "https://rubygems.org"
ruby RUBY_VERSION
gem "jekyll", "3.4.3"
gem "sass", "3.4.23"
gem "jekyll-toc"
gem "jekyll-last-modified-at"
gem "jekyll-sitemap"
gem "jekyll-pandoc"
gem "jekyll-s3"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

